version: "3.9"

services:
  shipping_api:
    build: .
    container_name: shipping
    command: >
      sh -c "gunicorn --workers 4 --bind 0.0.0.0:9002 main.wsgi:application"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "rabbitmq:host-gateway"
    ports:
      - "9002:9002"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - logs_volume:/app/logs
    env_file:
      - config.env
    networks:
      - shared-net
    restart: unless-stopped

  shipping_consumer:
    build: .
    container_name: shipping-consumer
    command: python manage.py consume_shipping_events
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "rabbitmq:host-gateway"
    volumes:
      - .:/app
      - logs_volume:/app/logs
    env_file:
      - config.env
    networks:
      - shared-net
    restart: unless-stopped

volumes:
  static_volume:
  logs_volume:

networks:
  shared-net:
    external: true
